# Generated by Django 3.1.2 on 2022-01-11 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0007_auto_20220111_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('1', '1コマ'), ('2', '2コマ'), ('3', '3コマ'), ('4', '4コマ'), ('5', '5コマ'), ('6', '6コマ')], max_length=10, null=True)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('r_university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.university')),
            ],
        ),
        migrations.CreateModel(
            name='MenuMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('weekday', models.CharField(choices=[('Mon', 'Monday'), ('Tue', 'Tuesday'), ('Wed', 'Wednesday'), ('Thu', 'Thursday'), ('Fry', 'Fryday'), ('Sat', 'Saturday'), ('Sun', 'Sunday')], max_length=10)),
                ('coma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_start_time', to='editlecture.coma')),
                ('finish_coma', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='range_finish_time', to='editlecture.coma')),
                ('major', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.major')),
                ('start_coma', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='range_start_time', to='editlecture.coma')),
            ],
        ),
        migrations.CreateModel(
            name='RegisterMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='editlecture.menumaster')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='menumaster',
            name='student',
            field=models.ManyToManyField(through='editlecture.RegisterMenu', to=settings.AUTH_USER_MODEL),
        ),
    ]
