# Generated by Django 3.1.2 on 2022-01-08 07:52

from django.db import migrations, models
import ulid.api.api


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20220108_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='edituser',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, verbose_name='ニックネーム'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='nickname',
            field=models.CharField(blank=True, max_length=32, verbose_name='ニックネーム'),
        ),
        migrations.AlterField(
            model_name='edituser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentuser',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(default=ulid.api.api.Api.new, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
